name: Policy as Code â€“ Conftest Check

on:
  pull_request:
  push:
    paths:
      - "policy-as-code/**"

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.62.0/conftest_0.62.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.62.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run policy checks
        run: |
          cd policy-as-code/lab-01-no-public-s3
          conftest test input.json --all-namespaces
